linters-settings:
  govet:
    enable:
      - shadow

linters:
  disable-all: true
  enable:
    - staticcheck
    - gofmt
    - govet
    - gocritic
    - unused
    - errcheck
    - gosimple
    - typecheck
    - misspell
    - goimports
    - gosec
    - ineffassign
    - unconvert
    - unparam
    - err113
    - errname
    - errorlint
    - nilerr
    - nilnil
    - wrapcheck