name: "cls3-action"
author: "k.goto"
description: "Run cls3 in GitHub Actions"
branding:
  icon: "command"
  color: "blue"
inputs:
  bucket-name:
    description: "Names of one or multiple buckets you want to delete (comma separated)"
    required: false
  force:
    description: "ForceMode (Delete the bucket together)"
    default: false
    required: false
  quiet:
    description: "Hide live display of number of deletions (default: true in GitHub Actions ONLY.)"
    default: true
    required: false
  old-versions-only:
    description: "Delete old version objects only (including all delete-markers)"
    default: false
    required: false
  directory-buckets-mode:
    description: "Clear Directory Buckets for S3 Express One Zone"
    default: false
    required: false
  table-buckets-mode:
    description: "Clear Table Buckets for S3 Tables"
    default: false
    required: false
  region:
    description: "AWS Region"
    default: "us-east-1"
    required: false
  concurrent-mode:
    description: "Delete multiple buckets in parallel"
    default: false
    required: false
  concurrency-number:
    description: "Specify the number of parallel deletions (requires concurrent-mode to be true)"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -eu
        if [ ! -e /usr/local/bin/cls3 ]; then
          DOWNLOAD_URL=$(curl https://api.github.com/repos/go-to-k/cls3/releases/latest | jq -r '.assets[].browser_download_url|select(match("Linux_x86_64."))')
          cd /tmp
          curl -sfLO ${DOWNLOAD_URL}
          FILENAME=$(basename $DOWNLOAD_URL)
          tar xzvf ${FILENAME}
          chmod +x cls3
          sudo mv cls3 /usr/local/bin/
          rm ${FILENAME}
        fi        
        if [ -n "${{ inputs.bucket-name }}" ]; then
          buckets=""
          for bucket in $(echo ${{ inputs.bucket-name }} | tr ',' ' '); do
            buckets="${buckets}-b ${bucket} "
          done
          force=""
          if [ "${{ inputs.force }}" = "true" ]; then
            force="-f"
          fi
          quiet=""
          if [ "${{ inputs.quiet }}" = "true" ]; then
            quiet="-q"
          fi
          old_versions_only=""
          if [ "${{ inputs.old-versions-only }}" = "true" ]; then
            old_versions_only="-o"
          fi
          directory_buckets_mode=""
          if [ "${{ inputs.directory-buckets-mode }}" = "true" ]; then
            directory_buckets_mode="-d"
          fi
          table_buckets_mode=""
          if [ "${{ inputs.table-buckets-mode }}" = "true" ]; then
            table_buckets_mode="-t"
          fi
          concurrent_mode=""
          if [ "${{ inputs.concurrent-mode }}" = "true" ]; then
            concurrent_mode="-c"
          fi
          concurrency_number=""
          if [ -n "${{ inputs.concurrency-number }}" ]; then
            concurrency_number="-n ${{ inputs.concurrency-number }}"
          fi
          region=""
          if [ -n "${{ inputs.region }}" ]; then
            region="-r ${{ inputs.region }}"
          fi
          cls3 $buckets $force $quiet $old_versions_only $directory_buckets_mode $table_buckets_mode $concurrent_mode $concurrency_number $region
        fi