// Code generated by MockGen. DO NOT EDIT.
// Source: bucket_selector.go
//
// Generated by this command:
//
//	mockgen -source=bucket_selector.go -destination=mock_bucket_selector.go -package=app -write_package_comment=false
//

package app

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIBucketSelector is a mock of IBucketSelector interface.
type MockIBucketSelector struct {
	ctrl     *gomock.Controller
	recorder *MockIBucketSelectorMockRecorder
	isgomock struct{}
}

// MockIBucketSelectorMockRecorder is the mock recorder for MockIBucketSelector.
type MockIBucketSelectorMockRecorder struct {
	mock *MockIBucketSelector
}

// NewMockIBucketSelector creates a new mock instance.
func NewMockIBucketSelector(ctrl *gomock.Controller) *MockIBucketSelector {
	mock := &MockIBucketSelector{ctrl: ctrl}
	mock.recorder = &MockIBucketSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBucketSelector) EXPECT() *MockIBucketSelectorMockRecorder {
	return m.recorder
}

// SelectBuckets mocks base method.
func (m *MockIBucketSelector) SelectBuckets(ctx context.Context) ([]string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBuckets", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectBuckets indicates an expected call of SelectBuckets.
func (mr *MockIBucketSelectorMockRecorder) SelectBuckets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBuckets", reflect.TypeOf((*MockIBucketSelector)(nil).SelectBuckets), ctx)
}
